#include <stdio.h>
#include <stdlib.h>

struct Node {
    int val;
    struct Node* next;
    struct Node* prev;
} typedef Node;

struct Deque {
    Node* head;
    Node* tail;
} typedef Deque;
// TODO

typedef enum {true = 1, false = 0} bool;

void enqueue_back(Deque* queue, int val);
void enqueue_front(Deque* queue, int val);

void dequeue_front(Deque* queue); 
void dequeue_back(Deque* queue); 

bool contains(Deque* queue, int val);

void print(Deque* queue);
void freeAll(Deque* queue);

// this is infallible, if not for the malloc
// only if the sysem fails to allocate the memory
// this function fails
/// pushes `val` to the back of the queue
void enqueue_back(Deque* queue, int val) {
    Node* node = malloc(sizeof(Node));
    node->val = val;
    node->next = NULL;
    node->prev = NULL;
    
    if (queue->head == NULL) {
        queue->head = node;
        queue->tail = node;
    } else {
        node->prev = queue->tail;
        queue->tail->next = node;
        queue->tail = node;
    }
}

/// pushes `val` to the front of the queue
void enqueue_front(Deque* queue, int val) {
    Node* node = malloc(sizeof(Node));
    node->val = val;
    node->next = NULL;
    node->prev = NULL;
    
    if (queue->head == NULL) {
        queue->head = node;
        queue->tail = node;
    } else {
        node->next = queue->head;
        queue->head->prev = node;
        queue->head = node;
    }
}

void dequeue_front(Deque* queue) {
    // TODO
} 

void dequeue_back(Deque* queue) {
    // TODO
}

/// checks if the queue contains a certain value
///
/// # Params
/// 
/// `queue` a `Deque` pointer of the queue to check
/// `val` an `int` representing the value to check
/// 
/// # Returns
/// `1` if the value is found
/// `0` if the queue is empty or the value is not found
bool contains(Deque* queue, int val) {
    if (queue->head == NULL) {
        return false;
    }
    Node* cursor = queue->head;
    while (cursor != NULL) {
        if (cursor->val == val) {
            return true;
        } else {
            cursor = cursor->next;
        }
    }
    return false;
}

/// pretty prints the queue
void print(Deque* queue) {
    // this way i create a pointer that is pointing to the same value as head
    Node* cursor = queue->head; 
    int idx = 0;
    while (cursor != NULL) {
        printf("queue[%d] = %d\n", idx, cursor->val);
        cursor = cursor->next;
        idx++;
    }
}

/// frees all the memory allocated by the queue
void freeAll(Deque* queue) {
    Node* current = queue->head;
    while (current != NULL) {
        Node* next = current->next;
        free(current);
        current = next;
    }
}

// some random testing generated by chatGPT
// TODO make chatGPT generate tests
